name: poll_chat
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+11

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get: ^4.6.6
  shared_preferences: ^2.2.1
  http: ^1.2.1
  fluttertoast: ^8.2.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  # image_picker: ^1.1.2
  image_picker: ^1.1.0
  video_player: ^2.2.5
  chewie: 1.8.5
  card_swiper: ^3.0.1
  flutter_share: ^2.0.0
  cached_network_image: ^3.2.0
  # camera: ^0.11.0+1
  camera: ^0.11.0
  flutter_sound: ^9.4.18
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  path_provider: ^2.0.1
  timeago: ^3.0.2
  story_view: ^0.16.5
  web_socket_channel: ^3.0.0
  sdp_transform: ^0.3.2
  socket_io_client: ^2.0.3+1
  flutter_ringtone_player: ^4.0.0+2
  flutter_background: ^1.2.0
  geolocator: ^12.0.0
  url_launcher: ^6.2.6
  flutter_file_downloader: ^2.0.0
  # video_watermark: ^1.0.5
  dio: ^5.1.1
  # image_editor: ^1.5.1
  image_editor: 1.4.0
  image: ^4.0.17
  path: ^1.9.0
  shimmer: ^3.0.0
  flutter_colorpicker: ^1.1.0
  curved_navigation_bar: ^1.0.3
  connectivity_plus: ^6.0.3
  font_awesome_flutter: ^10.7.0
  video_thumbnail: ^0.5.3
  timezone: ^0.9.3
  ffmpeg_kit_flutter_min: ^6.0.3
  flutter_windowmanager: ^0.2.0
  file_picker:
  hexagon: ^0.2.0
  change_app_package_name: ^1.3.0
  win32: ^5.5.0
  image_editor_common: 1.1.2
  # ffmpeg_kit_flutter:
  #   path: ffmpeg-kit-v4.5.1 # Replace with local path

  # flutter_ffmpeg: ^0.4.0

  # video_trimmer: ^3.0.1
  # video_editor_2: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/view/forgot_password/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
