///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PrivacyModelPrivacySetting {
/*
{
  "commentType": "everyone",
  "messageType": "friends",
  "profileType": "everyone",
  "storyType": "friends"
}
*/

  String? commentType;
  String? messageType;
  String? profileType;
  String? storyType;

  PrivacyModelPrivacySetting({
    this.commentType,
    this.messageType,
    this.profileType,
    this.storyType,
  });
  PrivacyModelPrivacySetting.fromJson(Map<String, dynamic> json) {
    commentType = json['commentType']?.toString();
    messageType = json['messageType']?.toString();
    profileType = json['profileType']?.toString();
    storyType = json['storyType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['commentType'] = commentType;
    data['messageType'] = messageType;
    data['profileType'] = profileType;
    data['storyType'] = storyType;
    return data;
  }
}

class PrivacyModel {
/*
{
  "success": true,
  "message": "Privacy Fetched Successfully",
  "privacySetting": {
    "commentType": "everyone",
    "messageType": "friends",
    "profileType": "everyone",
    "storyType": "friends"
  }
}
*/

  bool? success;
  String? message;
  PrivacyModelPrivacySetting? privacySetting;

  PrivacyModel({
    this.success,
    this.message,
    this.privacySetting,
  });
  PrivacyModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    privacySetting = (json['privacySetting'] != null) ? PrivacyModelPrivacySetting.fromJson(json['privacySetting']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (privacySetting != null) {
      data['privacySetting'] = privacySetting!.toJson();
    }
    return data;
  }
}
